### ISSUE TITLE
Using #pragma once interferes with proper function of rootcling for root 6.23.99

### ISSUE THREAD

**Issue by mholtrop** [JeffersonLab/clas12root#18]
This causes:
```
Fatal: ! (prop&kIsClass) && "Impossible code path" violated at line 462 of `.../TGenCollectionProxy.cxx'
aborting
```
Simple fix:
Remove `#pragma once` for a more traditional header gard.
Yes, unfortunate, because "#pragma once" is prettier, but in general, "#pragma" is compiler dependent.

**Comment by dglazier** [comment]
HI Maurik,

  Just checking if this is still a live issue as it has been closed. I would have hoped #pragma once would be OK in cling (as clang). Also was it just 6.23 this you have seen this issue? Eere there other versions that you were able to compile OK?

Cheers
Derek

**Comment by mholtrop** [comment]
Hi Derek,

Thank you for the follow up.
I pushed "submit" too quickly on that issue. Sorry, my bad. On closer inspection it seems to not be cling, and certainly not clang, that had issues with "#pragma once". Somehow though I cannot compile the clas12root code with the "master" root branch that I use for everything else. Over the next bit I will dig into this and will make a better issue report followed by a pull request.  That will also address the minor issue with casting, such as:

/data/CLAS12/clas12root/Clas12Root/ParticleTree.cpp:126:24: error: allocation of incomplete type 'TObjString'
      lines->AddAt(new TObjString("     _eventdata->ProcTime=evbank->getProcTime();"),place++);

There is also something strange going on with the rootcint step, which triggers an assert in the root code. That is likely a bug in root, but I would like find out exactly where. The difficulty is that it just stops and doesn't tell you what it was doing when it did. When I tried root version 6.20, I did not get that error, but did run into the casting issues. 

All and all, a bit of a challenging beginning for just wanting to take a look.  ¯\_(ツ)_/¯

Best,
	Maurik

**Comment by dglazier** [comment]
Hi Maurik,
  Possibly there is now a needed #include <TObjString.h> in ParticleTree.cpp, I think ROOT tidied up their #includes recently.
  Thanks for looking into the code, any suggestions or pull requests very welcome!
Cheers
Derek

**Comment by mholtrop** [comment]
Thanks.
I escalated the initial error. See: https://sft.its.cern.ch/jira/browse/ROOT-11013
Best,
	Maurik

**Comment by dglazier** [comment]
I see. Note I already had an issue with this code as commented in the source. Before 6.20 I was able to use the "using" alias but then stopped parsing with 6.20 and I had to change to the full declaration.

//using data_addrs_to_func = std::vector<addrs_to_func_uptr>; //root V6.20 DOES NOT LIKE THIS
  using data_addrs_to_func = std::vector<std::unique_ptr<std::pair< void (*)(hipo::bank*,void *,int, int), void* >>>;//!


Also note that the ntuple_writer and reader classes are more speculative, (probably nobody is using them apart from me) and are based on the fact it is much faster to write to hipo files than trees to root files. So it is not required for reading clas12 DSTs but can be used for next step analysis if there is a great deal of data writing required.
