### ISSUE TITLE
RTPC banks

### ISSUE THREAD

**Issue by sebouh137** [JeffersonLab/clas12root#24]
Could you add support for the RTPC?  Ie, by including the particles that were measured in the RTPC to those accessible using methods such as clas12reader::getByID().  This will allow us to do analyses in clas12root using runs from a certain range in which the RTCP was used in place of the CVT.  Thanks.

**Comment by dglazier** [comment]
Yes, that is a very important suggestion. Some questions,
Is RTPC a stand alone detector system or can particles give hits in ToF detectors also ?
Is CToF present during RTPC runs ?
What is the detector and layer numbering scheme for RTPC ?
Which DST bank REC::Response are associated with particles from RTPC ? REC::Trck ?

**Comment by baltzell** [comment]
The RTPC essentially replaces CVT, and the only difference in the DSTs would be the value of REC::Track.detector, which would be 19 for RTPC:

https://github.com/JeffersonLab/clas12-offline-software/blob/c030b8c44021976abdad080792d0d571bd3dc729/common-tools/clas-detector/src/main/java/org/jlab/detector/base/DetectorType.java#L27

**Comment by dglazier** [comment]
Thanks Nathan, That should make it very straightforward...

**Comment by dglazier** [comment]
Is there any layer numbering for RTPC
For example the CVT has 12 layers which just have numbering 1-12, aliased to CVT1,CVT2,...
Whereas the DC numbering for layers is 6,12,18 which are aliased to DC1,DC2,..

**Comment by baltzell** [comment]
In general they're all really 1 through N, but only a subset appears in the trajectory bank (which is the only place tracking layers appear in DSTs) to save space, and I don't think BONuS is there yet.

**Comment by dglazier** [comment]
Actually checking the DST wiki, it should go 1,2,3,...N so my question is what is N ?

**Comment by dglazier** [comment]
I have added RTPC to the github master. You can just use the raw integrer values for layer numbers if needed.
Sebouh, could you test this on a file and let me know if it works OK ?
