### ISSUE TITLE
distinguish between final-state, initial-state and intermediate-state MC particles 

### ISSUE THREAD

**Issue by sebouh137** [JeffersonLab/clas12root#29]
currently, I don't see a way to distinguish between MC particles in the initial, intermediate and final states.  I'd like to be able to loop over only the _final-state_ generated particles and compare them to the reconstructed particles for efficiency and resolution studies.

**Comment by dglazier** [comment]
Is it not sufficient to use the value of getPid ?
Note in the development version we have added the full Lund Particle information which is now in the hipo files
[dev macparticle](https://github.com/dglazier/clas12root/blob/master/Clas12Banks/mcparticle.h)
Also we hope to add the new mc-matching banks. Hopefully this will be released next week.
