### ISSUE TITLE
Issue with reading in "weight" from MC::Event bank

### ISSUE THREAD

**Issue by esteejus** [JeffersonLab/clas12root#32]
I'm reading in the MC::Event bank and getting the "weight". It seems the GEMC documentation on the LUND file input format, it looks like the weight was intended to be formatted as a Float. 

When I look at clas12root/Clas12Banks/mcevent.h I see on L44:
`float    getWeight() const noexcept { return getShort(_weight_order,_entry);}`
which looks a bit contradictory returning a Float but expecting a Short. I get the following error with the current master branch:
`---> error : requested SHORT for [weight] type = 4`

I've confirmed that changing to:
`float    getWeight() const noexcept { return getFloat(_weight_order,_entry);}` 
properly reads in the weight correctly. For now I can work around this by formatting the weight as a Short for now and then scale it back later, but I wonder if it was intended for weight to be a Float in the first place.

**Comment by dglazier** [comment]
You are correct, thanks for the bug report. I have updated the master branch and will release a tag 1.7.1 if you are happy with the fix.
Cheers
Derek

**Comment by esteejus** [comment]
I've tested the tag works great! Thank you!
