### ISSUE TITLE
Issues with LD_LIBRARY_PATH on farm

### ISSUE THREAD

**Issue by esteejus** [JeffersonLab/clas12root#34]
When installing my own local copy of clas12root right after successful compilation it seems everything runs fine, but once I log off the farm and log back on I get the following error when loading clas12root

`cling::DynamicLibraryManager::loadLibrary(): libccdb.so: cannot open shared object file: No such file or directory
cling::DynamicLibraryManager::loadLibrary(): libClas12Banks.so: cannot open shared object file: No such file or directory
`
Adding the library paths to LD_LIBRARY_PATH seems to fix this as in:
`setenv LD_LIBRARY_PATH $CLAS12ROOT/lib:$CLAS12ROOT/ccdb/lib:$LD_LIBRARY_PATH
`
Is this path being setup somewhere else that I am somehow missing in the installation, or should I be adding my above line in when loading my environmental variables anyway? 

Thanks!

**Comment by dglazier** [comment]
You are correct that the library path needs set. This is included in the instructions in the README for cshrc, but is missing for bash,

    setenv CCDB_HOME /Where/Is/ccdb   (e.g. setenv CCDB_HOME ${CLAS12ROOT}/ccdb )
    source ${CCDB_HOME}/environment.csh

i.e. it gets set in  ${CCDB_HOME}/environment.csh
I will update the bash instructions

**Comment by esteejus** [comment]
I'm sorry I should have more carefully read the README! Thank you for your help as always!
