### ISSUE TITLE
Out of scope variable in qadb_reader

### ISSUE THREAD

**Issue by sfegan84** [JeffersonLab/clas12root#59]
Function qadb_reader::getChargeForRunlist contains out of scope variable '_qa'. A fresh install of clas12root from a git clone of the code as it stands returns an error when reaching this part of the build of Clas12Banks

**Comment by dglazier** [comment]
Hi Stuart,
  Thanks for reporting. I am unable to reproduce this on my laptop for some reason. But it looks like it can probably happen if you do not have 

   setenv QADB ${CLAS12ROOT}/clas12-qadb

If you set this variable as above does it still not work ?
Cheers
Derek

**Comment by sfegan84** [comment]
Hi Derek,
On further investigation, I can only reproduce this on York-managed systems with the current version.  Local machines (Fedora and Ubuntu on WSL), seem to be fine.  For now, I've set our new students up with an older version I run on my laptop, which compiles just fine on the York system and will allow them to start looking at data.  I'll drill into this some more and keep this tread updated

**Comment by dglazier** [comment]
Hi Stuart,
  Can you confirm that you get the error on the York machines with setenv QADB ${CLAS12ROOT}/clas12-qadb
 And how would you describe the York system modern, a bit-dated, ancient ?
Cheers
Derek

**Comment by dglazier** [comment]
OK, please close the issue if you think it is done

**Comment by sfegan84** [comment]
Will do, thanks for your help
