### ISSUE TITLE
Ready for deployment

### ISSUE THREAD

**Issue by dglazier** [JeffersonLab/clas12root#70]
@baltzell , @c-dilks 

I would like to deploy the current main branch on ifarm. It requires hipo 4.1.0 and a suitably recent iguana (e.g. dev/4.1.0). So this probably needs these packages to be made "pro". Is there plans for when this might happen ? I will tag clas12root when we have a date.

Also I think the ROOT_INCLUDE_PATH not removing packages might have been iguana rather than clas12root. When I module unload iguana it remains in the ROOT_INCLUDE_PATH.

We also need 
export ROOT_INCLUDE_PATH=/scigroup/cvmfs/hallb/clas12/soft/almalinux9-gcc11/include:$ROOT_INCLUDE_PATH
so it does not use  /usr/local/fmt, this may be part of a recent iguana release anyway.

Cheers
Derek

**Comment by c-dilks** [comment]
Can you make a new tag and release? Then we can update the module files.

**Comment by dglazier** [comment]
Sure will do, as long as you are happy with the current iguana dev and hipo
