### ISSUE TITLE
Build failure with external $CCDB_HOME

### ISSUE THREAD

**Issue by baltzell** [JeffersonLab/clas12root#78]
ccdb_reader.h:6:10: fatal error: 'CCDB/CalibrationGenerator.h' file not found

**Comment by dglazier** [comment]
Does this need $CCDB_HOME/include/CCDB/ added to $ROOT_INCLUDE_PATH ?
Did something change to cause this ?

**Comment by baltzell** [comment]
nope, same old ccdb builds and env setup

**Comment by baltzell** [comment]
Ok, sorry, I think I know what happened ... Until early/mid last year, with the software builds and environment at JLab, in certain cases you could fall back to a version of CCDB built with scons.   Last winter the main jeffersonlab/CCDB branch(es?) switched to cmake and dropped scons support, and so did our new CCDB installations at JLab.  And they apparently have a different install structure, which went unnoticed until trying to build clas12root after the environment bug was removed.
